export { default as Login } from "./Login"
export { default as Home } from "./Home"
export { default as Albums } from "./Albums"
export { default as Feedback } from "./Feedback"
export { default as NotFound } from "./NotFound"
